// AUTO-GENERATED by tinyinfer-agent (memory skill). DO NOT EDIT BY HAND.
// Guard-band tests: sentinel bytes around the active buffer must remain
// untouched after the op runs. Rebuild with -fsanitize=address for full
// leak / UAF coverage.
#include "tinyinfer/matmul.hpp"

#include <gtest/gtest.h>

#include <cstddef>
#include <cstdint>
#include <vector>

namespace {
constexpr std::uint32_t kGuard = 0xDEADBEEFu;

// Allocate `n` floats with one guard word on each side. Returns the
// address of the active region and stamps guard words into the padding.
inline float* make_guarded(std::vector<std::uint32_t>& storage, std::size_t n_floats) {
    // 1 guard word + n_floats words + 1 guard word, all uint32-sized.
    storage.assign(n_floats + 2, 0u);
    storage.front() = kGuard;
    storage.back() = kGuard;
    return reinterpret_cast<float*>(&storage[1]);
}

inline bool guards_intact(const std::vector<std::uint32_t>& storage) {
    return storage.front() == kGuard && storage.back() == kGuard;
}
}

TEST(MatmulMemory, memory_guard_bands_small) {
    constexpr std::size_t m = 4, k = 4, n = 4;
    for (int it = 0; it < 256; ++it) {
        std::vector<std::uint32_t> sa, sb, sc;
        float* a = make_guarded(sa, m * k);
        float* b = make_guarded(sb, k * n);
        float* c = make_guarded(sc, m * n);
        for (std::size_t i = 0; i < m * k; ++i) a[i] = 0.5f;
        for (std::size_t i = 0; i < k * n; ++i) b[i] = 0.25f;

        ASSERT_TRUE(tinyinfer::matmul_fp32(a, b, c, m, k, n));

        EXPECT_TRUE(guards_intact(sa)) << "input A guard clobbered at iter " << it;
        EXPECT_TRUE(guards_intact(sb)) << "input B guard clobbered at iter " << it;
        EXPECT_TRUE(guards_intact(sc)) << "output C guard clobbered at iter " << it;
    }
}

TEST(MatmulMemory, memory_repeat_alloc_medium) {
    constexpr std::size_t m = 16, k = 32, n = 16;
    for (int it = 0; it < 64; ++it) {
        std::vector<std::uint32_t> sa, sb, sc;
        float* a = make_guarded(sa, m * k);
        float* b = make_guarded(sb, k * n);
        float* c = make_guarded(sc, m * n);
        for (std::size_t i = 0; i < m * k; ++i) a[i] = 0.5f;
        for (std::size_t i = 0; i < k * n; ++i) b[i] = 0.25f;

        ASSERT_TRUE(tinyinfer::matmul_fp32(a, b, c, m, k, n));

        EXPECT_TRUE(guards_intact(sa)) << "input A guard clobbered at iter " << it;
        EXPECT_TRUE(guards_intact(sb)) << "input B guard clobbered at iter " << it;
        EXPECT_TRUE(guards_intact(sc)) << "output C guard clobbered at iter " << it;
    }
}
