// AUTO-GENERATED by tinyinfer-agent (perf skill). DO NOT EDIT BY HAND.
// chrono-based microbenchmarks emitted as GTest cases. Budgets are loose:
// the intent is to catch order-of-magnitude regressions, not certify perf.
#include "tinyinfer/softmax.hpp"

#include <gtest/gtest.h>

#include <algorithm>
#include <chrono>
#include <cstddef>
#include <vector>

namespace {
inline double median_us(std::vector<double> ts) {
    std::sort(ts.begin(), ts.end());
    const std::size_t n = ts.size();
    if (n == 0) return 0.0;
    return (n % 2 == 1) ? ts[n / 2] : 0.5 * (ts[n / 2 - 1] + ts[n / 2]);
}
}

TEST(SoftmaxPerf, perf_small_n32) {
    constexpr std::size_t n = 32;
    std::vector<float> x(n, 0.5f);
    std::vector<float> y(n, 0.0f);

    for (int w = 0; w < 5; ++w) { tinyinfer::softmax_fp32(x.data(), y.data(), n); }

    std::vector<double> samples;
    samples.reserve(500);
    for (int i = 0; i < 500; ++i) {
        const auto t0 = std::chrono::steady_clock::now();
        tinyinfer::softmax_fp32(x.data(), y.data(), n);
        const auto t1 = std::chrono::steady_clock::now();
        samples.push_back(
            std::chrono::duration<double, std::micro>(t1 - t0).count());
    }
    const double med = median_us(samples);
    EXPECT_LT(med, 50) << "median per-iter latency exceeded budget";
}

TEST(SoftmaxPerf, perf_aligned_n128) {
    constexpr std::size_t n = 128;
    std::vector<float> x(n, 0.5f);
    std::vector<float> y(n, 0.0f);

    for (int w = 0; w < 5; ++w) { tinyinfer::softmax_fp32(x.data(), y.data(), n); }

    std::vector<double> samples;
    samples.reserve(200);
    for (int i = 0; i < 200; ++i) {
        const auto t0 = std::chrono::steady_clock::now();
        tinyinfer::softmax_fp32(x.data(), y.data(), n);
        const auto t1 = std::chrono::steady_clock::now();
        samples.push_back(
            std::chrono::duration<double, std::micro>(t1 - t0).count());
    }
    const double med = median_us(samples);
    EXPECT_LT(med, 200) << "median per-iter latency exceeded budget";
}

TEST(SoftmaxPerf, perf_thin_n8) {
    constexpr std::size_t n = 8;
    std::vector<float> x(n, 0.5f);
    std::vector<float> y(n, 0.0f);

    for (int w = 0; w < 5; ++w) { tinyinfer::softmax_fp32(x.data(), y.data(), n); }

    std::vector<double> samples;
    samples.reserve(1000);
    for (int i = 0; i < 1000; ++i) {
        const auto t0 = std::chrono::steady_clock::now();
        tinyinfer::softmax_fp32(x.data(), y.data(), n);
        const auto t1 = std::chrono::steady_clock::now();
        samples.push_back(
            std::chrono::duration<double, std::micro>(t1 - t0).count());
    }
    const double med = median_us(samples);
    EXPECT_LT(med, 20) << "median per-iter latency exceeded budget";
}
