// AUTO-GENERATED by tinyinfer-agent (perf skill). DO NOT EDIT BY HAND.
// chrono-based microbenchmarks emitted as GTest cases. Budgets are loose:
// the intent is to catch order-of-magnitude regressions, not certify perf.
#include "tinyinfer/matmul.hpp"

#include <gtest/gtest.h>

#include <algorithm>
#include <chrono>
#include <cstddef>
#include <vector>

namespace {
inline double median_us(std::vector<double> ts) {
    std::sort(ts.begin(), ts.end());
    const std::size_t n = ts.size();
    if (n == 0) return 0.0;
    return (n % 2 == 1) ? ts[n / 2] : 0.5 * (ts[n / 2 - 1] + ts[n / 2]);
}
}

TEST(MatmulPerf, perf_small_16x16x16) {
    constexpr std::size_t m = 16, k = 16, n = 16;
    std::vector<float> a(m * k, 0.5f);
    std::vector<float> b(k * n, 0.25f);
    std::vector<float> c(m * n, 0.0f);

    // Warmup.
    for (int w = 0; w < 5; ++w) {
        tinyinfer::matmul_fp32(a.data(), b.data(), c.data(), m, k, n);
    }

    std::vector<double> samples;
    samples.reserve(200);
    for (int i = 0; i < 200; ++i) {
        const auto t0 = std::chrono::steady_clock::now();
        tinyinfer::matmul_fp32(a.data(), b.data(), c.data(), m, k, n);
        const auto t1 = std::chrono::steady_clock::now();
        samples.push_back(
            std::chrono::duration<double, std::micro>(t1 - t0).count());
    }
    const double med = median_us(samples);
    EXPECT_LT(med, 200) << "median per-iter latency exceeded budget";
}

TEST(MatmulPerf, perf_medium_64x64x64) {
    constexpr std::size_t m = 64, k = 64, n = 64;
    std::vector<float> a(m * k, 0.5f);
    std::vector<float> b(k * n, 0.25f);
    std::vector<float> c(m * n, 0.0f);

    // Warmup.
    for (int w = 0; w < 5; ++w) {
        tinyinfer::matmul_fp32(a.data(), b.data(), c.data(), m, k, n);
    }

    std::vector<double> samples;
    samples.reserve(50);
    for (int i = 0; i < 50; ++i) {
        const auto t0 = std::chrono::steady_clock::now();
        tinyinfer::matmul_fp32(a.data(), b.data(), c.data(), m, k, n);
        const auto t1 = std::chrono::steady_clock::now();
        samples.push_back(
            std::chrono::duration<double, std::micro>(t1 - t0).count());
    }
    const double med = median_us(samples);
    EXPECT_LT(med, 5000) << "median per-iter latency exceeded budget";
}

TEST(MatmulPerf, perf_aligned_32x32x32) {
    constexpr std::size_t m = 32, k = 32, n = 32;
    std::vector<float> a(m * k, 0.5f);
    std::vector<float> b(k * n, 0.25f);
    std::vector<float> c(m * n, 0.0f);

    // Warmup.
    for (int w = 0; w < 5; ++w) {
        tinyinfer::matmul_fp32(a.data(), b.data(), c.data(), m, k, n);
    }

    std::vector<double> samples;
    samples.reserve(100);
    for (int i = 0; i < 100; ++i) {
        const auto t0 = std::chrono::steady_clock::now();
        tinyinfer::matmul_fp32(a.data(), b.data(), c.data(), m, k, n);
        const auto t1 = std::chrono::steady_clock::now();
        samples.push_back(
            std::chrono::duration<double, std::micro>(t1 - t0).count());
    }
    const double med = median_us(samples);
    EXPECT_LT(med, 1500) << "median per-iter latency exceeded budget";
}
