// AUTO-GENERATED by tinyinfer-agent. DO NOT EDIT BY HAND.
// Reference values computed via numpy oracle.
#include "tinyinfer/softmax.hpp"

#include <gtest/gtest.h>

#include <cmath>
#include <vector>

TEST(SoftmaxGenerated, basic_1d_n8) {
    // 1D simplest case
    constexpr std::size_t rows = 1;
    constexpr std::size_t cols = 8;
    std::vector<float> x = {0.3047171f, -1.039984f, 0.7504512f, 0.9405647f, -1.951035f, -1.302179f, 0.1278404f, -0.3162426f};
    std::vector<float> expected = {0.156458f, 0.04077571f, 0.2443305f, 0.2954901f, 0.01639597f, 0.03137122f, 0.1310935f, 0.08408498f};
    std::vector<float> y(rows * cols, 0.0f);

    for (std::size_t r = 0; r < rows; ++r) {
        ASSERT_TRUE(tinyinfer::softmax_fp32(x.data() + r * cols, y.data() + r * cols, cols));
    }
    ASSERT_EQ(y.size(), expected.size());
    for (std::size_t i = 0; i < expected.size(); ++i) {
        EXPECT_NEAR(y[i], expected[i], 1e-05f) << "mismatch at index " << i;
    }
}

TEST(SoftmaxGenerated, thin_1d_n3) {
    // very short vector — degenerate edge
    constexpr std::size_t rows = 1;
    constexpr std::size_t cols = 3;
    std::vector<float> x = {-0.01680116f, -0.8530439f, 0.879398f};
    std::vector<float> expected = {0.2574925f, 0.1115807f, 0.6309268f};
    std::vector<float> y(rows * cols, 0.0f);

    for (std::size_t r = 0; r < rows; ++r) {
        ASSERT_TRUE(tinyinfer::softmax_fp32(x.data() + r * cols, y.data() + r * cols, cols));
    }
    ASSERT_EQ(y.size(), expected.size());
    for (std::size_t i = 0; i < expected.size(); ++i) {
        EXPECT_NEAR(y[i], expected[i], 1e-05f) << "mismatch at index " << i;
    }
}

TEST(SoftmaxGenerated, batch_2d_axis_last_4x16) {
    // batched softmax along last axis
    constexpr std::size_t rows = 4;
    constexpr std::size_t cols = 16;
    std::vector<float> x = {0.7777919f, 0.0660307f, 1.127241f, 0.4675093f, -0.8592924f, 0.3687508f, -0.9588826f, 0.8784503f, -0.04992591f, -0.1848624f, -0.6809295f, 1.222541f, -0.1545295f, -0.4283278f, -0.3521335f, 0.5323092f, 0.3654441f, 0.4127326f, 0.430821f, 2.141648f, -0.406415f, -0.5122427f, -0.8137727f, 0.6159794f, 1.128972f, -0.1139475f, -0.8401565f, -0.8244812f, 0.6505928f, 0.7432542f, 0.5431542f, -0.6655097f, 0.2321613f, 0.1166858f, 0.2186886f, 0.8714288f, 0.2235955f, 0.6789135f, 0.06757907f, 0.2891194f, 0.6312882f, -1.457156f, -0.3196712f, -0.4703726f, -0.6388779f, -0.2751423f, 1.494941f, -0.8658311f, 0.9682783f, -1.68287f, -0.334885f, 0.1627531f, 0.5862224f, 0.7112266f, 0.7933472f, -0.3487251f, -0.4623518f, 0.8579759f, -0.1913043f, -1.275686f, -1.133287f, -0.9194523f, 0.4971607f, 0.1424257f};
    std::vector<float> expected = {0.0981058f, 0.04814828f, 0.1391421f, 0.07193507f, 0.01908613f, 0.06517039f, 0.01727693f, 0.1084951f, 0.0428767f, 0.03746444f, 0.02281287f, 0.1530548f, 0.03861826f, 0.02936862f, 0.0316938f, 0.0767508f, 0.0520767f, 0.0545985f, 0.05559507f, 0.3076372f, 0.02406741f, 0.02165055f, 0.0160146f, 0.06690362f, 0.111748f, 0.03224382f, 0.0155976f, 0.01584402f, 0.06925993f, 0.07598438f, 0.06220453f, 0.01857402f, 0.0592768f, 0.0528122f, 0.05848353f, 0.112335f, 0.05877121f, 0.09266307f, 0.05028142f, 0.06275108f, 0.0883534f, 0.0109452f, 0.03413712f, 0.02936149f, 0.02480831f, 0.03569156f, 0.2095574f, 0.01977118f, 0.1380729f, 0.009743822f, 0.0375104f, 0.06169829f, 0.09422877f, 0.1067756f, 0.1159142f, 0.03699483f, 0.03302125f, 0.123653f, 0.04330201f, 0.01464087f, 0.01688146f, 0.02090631f, 0.08619945f, 0.06045679f};
    std::vector<float> y(rows * cols, 0.0f);

    for (std::size_t r = 0; r < rows; ++r) {
        ASSERT_TRUE(tinyinfer::softmax_fp32(x.data() + r * cols, y.data() + r * cols, cols));
    }
    ASSERT_EQ(y.size(), expected.size());
    for (std::size_t i = 0; i < expected.size(); ++i) {
        EXPECT_NEAR(y[i], expected[i], 1.6e-05f) << "mismatch at index " << i;
    }
}

TEST(SoftmaxGenerated, stability_large_values_overflow) {
    // numerical stability on large logits
    constexpr std::size_t rows = 1;
    constexpr std::size_t cols = 3;
    std::vector<float> x = {1000.0f, 1001.0f, 1002.0f};
    std::vector<float> expected = {0.09003057f, 0.2447285f, 0.6652409f};
    std::vector<float> y(rows * cols, 0.0f);

    for (std::size_t r = 0; r < rows; ++r) {
        ASSERT_TRUE(tinyinfer::softmax_fp32(x.data() + r * cols, y.data() + r * cols, cols));
    }
    ASSERT_EQ(y.size(), expected.size());
    for (std::size_t i = 0; i < expected.size(); ++i) {
        EXPECT_NEAR(y[i], expected[i], 1e-05f) << "mismatch at index " << i;
    }
}

TEST(SoftmaxGenerated, stability_negative_inf_one_hot) {
    // near-one-hot logits stress the softmax tail
    constexpr std::size_t rows = 1;
    constexpr std::size_t cols = 4;
    std::vector<float> x = {0.0f, 0.0f, 100.0f, 0.0f};
    std::vector<float> expected = {3.783506e-44f, 3.783506e-44f, 1.0f, 3.783506e-44f};
    std::vector<float> y(rows * cols, 0.0f);

    for (std::size_t r = 0; r < rows; ++r) {
        ASSERT_TRUE(tinyinfer::softmax_fp32(x.data() + r * cols, y.data() + r * cols, cols));
    }
    ASSERT_EQ(y.size(), expected.size());
    for (std::size_t i = 0; i < expected.size(); ++i) {
        EXPECT_NEAR(y[i], expected[i], 1e-05f) << "mismatch at index " << i;
    }
}

TEST(SoftmaxGenerated, aligned_1d_n32) {
    // hardware-aligned length for SIMD softmax
    constexpr std::size_t rows = 1;
    constexpr std::size_t cols = 32;
    std::vector<float> x = {0.6904854f, -0.4272527f, 0.1585397f, 0.6255904f, -0.3093465f, 0.4567752f, -0.6619259f, -0.3630539f, -0.3817379f, -1.19584f, 0.4869725f, -0.4694023f, 0.01249412f, 0.4807467f, 0.4465312f, 0.6653851f, -0.09848548f, -0.4232983f, -0.07971821f, -1.687334f, -1.447112f, -1.3227f, -0.9972468f, 0.3997742f, -0.9054791f, -0.3781626f, 1.299228f, -0.356264f, 0.7375156f, -0.9336177f, -0.2054376f, -0.950022f};
    std::vector<float> expected = {0.06088605f, 0.01991088f, 0.03576817f, 0.05706033f, 0.02240249f, 0.04819687f, 0.0157461f, 0.02123105f, 0.02083805f, 0.00923203f, 0.04967448f, 0.01908908f, 0.03090793f, 0.04936617f, 0.04770565f, 0.05937682f, 0.02766127f, 0.01998977f, 0.0281853f, 0.005647338f, 0.007180768f, 0.008132098f, 0.01126017f, 0.04552642f, 0.01234239f, 0.02091269f, 0.1119158f, 0.0213757f, 0.06381794f, 0.01199993f, 0.02485555f, 0.01180469f};
    std::vector<float> y(rows * cols, 0.0f);

    for (std::size_t r = 0; r < rows; ++r) {
        ASSERT_TRUE(tinyinfer::softmax_fp32(x.data() + r * cols, y.data() + r * cols, cols));
    }
    ASSERT_EQ(y.size(), expected.size());
    for (std::size_t i = 0; i < expected.size(); ++i) {
        EXPECT_NEAR(y[i], expected[i], 3.2e-05f) << "mismatch at index " << i;
    }
}
