// AUTO-GENERATED by tinyinfer-agent. DO NOT EDIT BY HAND.
// Reference values computed via numpy oracle.
#include "tinyinfer/layernorm.hpp"

#include <gtest/gtest.h>

#include <cmath>
#include <vector>

TEST(LayernormGenerated, basic_1d_n4) {
    // smallest non-trivial 1D case
    constexpr std::size_t rows = 1;
    constexpr std::size_t cols = 4;
    constexpr float eps = 1e-05f;
    std::vector<float> x = {0.3047171f, -1.039984f, 0.7504512f, 0.9405647f};
    std::vector<float> expected = {0.08502897f, -1.653171f, 0.6611978f, 0.9069439f};
    std::vector<float> y(rows * cols, 0.0f);

    for (std::size_t r = 0; r < rows; ++r) {
        ASSERT_TRUE(tinyinfer::layernorm_fp32(
            x.data() + r * cols, y.data() + r * cols, cols,
            nullptr, nullptr, eps));
    }
    ASSERT_EQ(y.size(), expected.size());
    for (std::size_t i = 0; i < expected.size(); ++i) {
        EXPECT_NEAR(y[i], expected[i], 0.000165317f) << "mismatch at index " << i;
    }
}

TEST(LayernormGenerated, thin_1d_n2) {
    // length-2 vector — degenerate edge
    constexpr std::size_t rows = 1;
    constexpr std::size_t cols = 2;
    constexpr float eps = 1e-05f;
    std::vector<float> x = {0.0f, 1.0f};
    std::vector<float> expected = {-0.99998f, 0.99998f};
    std::vector<float> y(rows * cols, 0.0f);

    for (std::size_t r = 0; r < rows; ++r) {
        ASSERT_TRUE(tinyinfer::layernorm_fp32(
            x.data() + r * cols, y.data() + r * cols, cols,
            nullptr, nullptr, eps));
    }
    ASSERT_EQ(y.size(), expected.size());
    for (std::size_t i = 0; i < expected.size(); ++i) {
        EXPECT_NEAR(y[i], expected[i], 0.0001f) << "mismatch at index " << i;
    }
}

TEST(LayernormGenerated, batch_2d_4x16) {
    // batched layernorm along last axis
    constexpr std::size_t rows = 4;
    constexpr std::size_t cols = 16;
    constexpr float eps = 1e-05f;
    std::vector<float> x = {-1.951035f, -1.302179f, 0.1278404f, -0.3162426f, -0.01680116f, -0.8530439f, 0.879398f, 0.7777919f, 0.0660307f, 1.127241f, 0.4675093f, -0.8592924f, 0.3687508f, -0.9588826f, 0.8784503f, -0.04992591f, -0.1848624f, -0.6809295f, 1.222541f, -0.1545295f, -0.4283278f, -0.3521335f, 0.5323092f, 0.3654441f, 0.4127326f, 0.430821f, 2.141648f, -0.406415f, -0.5122427f, -0.8137727f, 0.6159794f, 1.128972f, -0.1139475f, -0.8401565f, -0.8244812f, 0.6505928f, 0.7432542f, 0.5431542f, -0.6655097f, 0.2321613f, 0.1166858f, 0.2186886f, 0.8714288f, 0.2235955f, 0.6789135f, 0.06757907f, 0.2891194f, 0.6312882f, -1.457156f, -0.3196712f, -0.4703726f, -0.6388779f, -0.2751423f, 1.494941f, -0.8658311f, 0.9682783f, -1.68287f, -0.334885f, 0.1627531f, 0.5862224f, 0.7112266f, 0.7933472f, -0.3487251f, -0.4623518f};
    std::vector<float> expected = {-2.17066f, -1.409394f, 0.2683675f, -0.25265f, 0.09866776f, -0.8824486f, 1.150128f, 1.030919f, 0.1958497f, 1.440908f, 0.6668819f, -0.8897797f, 0.5510141f, -1.006623f, 1.149016f, 0.05980435f, -0.5026751f, -1.138492f, 1.301215f, -0.463797f, -0.8147284f, -0.7170691f, 0.4165343f, 0.2026608f, 0.2632712f, 0.2864554f, 2.479247f, -0.7866425f, -0.9222834f, -1.308759f, 0.5237758f, 1.181286f, -0.5482815f, -1.919638f, -1.890037f, 0.8954586f, 1.070438f, 0.6925741f, -1.589839f, 0.1053023f, -0.112759f, 0.07986072f, 1.31248f, 0.0891269f, 0.9489388f, -0.205491f, 0.2128606f, 0.8590043f, -1.571225f, -0.2207931f, -0.3997072f, -0.599758f, -0.1679279f, 1.933531f, -0.869199f, 1.308272f, -1.839195f, -0.238855f, 0.3519453f, 0.8546918f, 1.003098f, 1.100592f, -0.2552861f, -0.3901847f};
    std::vector<float> y(rows * cols, 0.0f);

    for (std::size_t r = 0; r < rows; ++r) {
        ASSERT_TRUE(tinyinfer::layernorm_fp32(
            x.data() + r * cols, y.data() + r * cols, cols,
            nullptr, nullptr, eps));
    }
    ASSERT_EQ(y.size(), expected.size());
    for (std::size_t i = 0; i < expected.size(); ++i) {
        EXPECT_NEAR(y[i], expected[i], 0.000247925f) << "mismatch at index " << i;
    }
}

TEST(LayernormGenerated, stability_large_magnitude) {
    // large magnitudes stress mean/var accumulation
    constexpr std::size_t rows = 1;
    constexpr std::size_t cols = 8;
    constexpr float eps = 1e-05f;
    std::vector<float> x = {8579.759f, -1913.043f, -12756.86f, -11332.87f, -9194.522f, 4971.607f, 1424.257f, 6904.854f};
    std::vector<float> expected = {1.289086f, -0.03126217f, -1.39578f, -1.216594f, -0.9475177f, 0.835059f, 0.3886828f, 1.078326f};
    std::vector<float> y(rows * cols, 0.0f);

    for (std::size_t r = 0; r < rows; ++r) {
        ASSERT_TRUE(tinyinfer::layernorm_fp32(
            x.data() + r * cols, y.data() + r * cols, cols,
            nullptr, nullptr, eps));
    }
    ASSERT_EQ(y.size(), expected.size());
    for (std::size_t i = 0; i < expected.size(); ++i) {
        EXPECT_NEAR(y[i], expected[i], 0.000139578f) << "mismatch at index " << i;
    }
}

TEST(LayernormGenerated, stability_near_constant) {
    // near-constant input — variance ≈ 0 stresses eps path
    constexpr std::size_t rows = 1;
    constexpr std::size_t cols = 4;
    constexpr float eps = 1e-05f;
    std::vector<float> x = {1.0f, 1.0f, 1.0f, 1.0001f};
    std::vector<float> expected = {-0.007915689f, -0.007915689f, -0.007915689f, 0.02370937f};
    std::vector<float> y(rows * cols, 0.0f);

    for (std::size_t r = 0; r < rows; ++r) {
        ASSERT_TRUE(tinyinfer::layernorm_fp32(
            x.data() + r * cols, y.data() + r * cols, cols,
            nullptr, nullptr, eps));
    }
    ASSERT_EQ(y.size(), expected.size());
    for (std::size_t i = 0; i < expected.size(); ++i) {
        EXPECT_NEAR(y[i], expected[i], 0.0001f) << "mismatch at index " << i;
    }
}

TEST(LayernormGenerated, aligned_1d_n32) {
    // hardware-aligned length for SIMD layernorm
    constexpr std::size_t rows = 1;
    constexpr std::size_t cols = 32;
    constexpr float eps = 1e-05f;
    std::vector<float> x = {-0.4272527f, 0.1585397f, 0.6255904f, -0.3093465f, 0.4567752f, -0.6619259f, -0.3630539f, -0.3817379f, -1.19584f, 0.4869725f, -0.4694023f, 0.01249412f, 0.4807467f, 0.4465312f, 0.6653851f, -0.09848548f, -0.4232983f, -0.07971821f, -1.687334f, -1.447112f, -1.3227f, -0.9972468f, 0.3997742f, -0.9054791f, -0.3781626f, 1.299228f, -0.356264f, 0.7375156f, -0.9336177f, -0.2054376f, -0.950022f, -0.3390331f};
    std::vector<float> expected = {-0.2466427f, 0.5925776f, 1.261686f, -0.07772756f, 1.019837f, -0.5828414f, -0.15467f, -0.1814372f, -1.347739f, 1.063098f, -0.3070274f, 0.3833492f, 1.054179f, 1.005161f, 1.318697f, 0.2243571f, -0.2409776f, 0.2512436f, -2.051867f, -1.707719f, -1.529482f, -1.06323f, 0.9381761f, -0.9317615f, -0.1763151f, 2.226756f, -0.1449426f, 1.422033f, -0.9720736f, 0.07113496f, -0.995575f, -0.1202572f};
    std::vector<float> y(rows * cols, 0.0f);

    for (std::size_t r = 0; r < rows; ++r) {
        ASSERT_TRUE(tinyinfer::layernorm_fp32(
            x.data() + r * cols, y.data() + r * cols, cols,
            nullptr, nullptr, eps));
    }
    ASSERT_EQ(y.size(), expected.size());
    for (std::size_t i = 0; i < expected.size(); ++i) {
        EXPECT_NEAR(y[i], expected[i], 0.000222676f) << "mismatch at index " << i;
    }
}
