"""Render generated test cases to GTest C++ source files.

We deliberately do NOT ask the LLM to emit raw C++ code for numerical tests —
the LLM picks shapes / dtypes / edges, but the actual numerical values come
from the numpy oracle and we template the C++ ourselves. This is the
"evidence-grounded test generation" story that goes in the devlog.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np


@dataclass
class RenderedTest:
    file_name: str
    test_suite: str
    cpp_source: str


_HEADER = """\
// AUTO-GENERATED by tinyinfer-agent. DO NOT EDIT BY HAND.
// Reference values computed via numpy oracle.
#include "tinyinfer/{header}"

#include <gtest/gtest.h>

#include <cmath>
#include <vector>
"""


def _fmt_float_array(arr: np.ndarray) -> str:
    flat = np.asarray(arr, dtype=np.float32).reshape(-1)
    return ", ".join(_fmt_float(v) for v in flat.tolist())


def _fmt_float(v: float) -> str:
    """Format a single float as a valid C++ literal.

    `f"{v:.7g}f"` is unsafe: integer-valued floats render as e.g. "1f",
    which C++ rejects (no decimal point or exponent). Force a trailing
    decimal so the result is always a well-formed float literal.
    """
    s = f"{v:.7g}"
    if not any(c in s for c in (".", "e", "E", "n", "i")):  # n/i catch nan/inf
        s = s + ".0"
    return s + "f"


def render_matmul_test(
    *,
    suite: str,
    case_name: str,
    a: np.ndarray,
    b: np.ndarray,
    expected: np.ndarray,
    m: int,
    k: int,
    n: int,
    tol: float | None = None,
    rationale: str = "",
) -> str:
    # Auto-scale tolerance with output magnitude. fp32 carries ~7 decimal
    # digits, so we use a 1e-5 relative tolerance with a 1e-4 absolute floor.
    if tol is None:
        max_abs = float(np.max(np.abs(expected))) if expected.size else 0.0
        tol = max(1e-4, max_abs * 1e-5)

    return f"""\
TEST({suite}, {case_name}) {{
    // {rationale}
    std::vector<float> a = {{{_fmt_float_array(a)}}};
    std::vector<float> b = {{{_fmt_float_array(b)}}};
    std::vector<float> expected = {{{_fmt_float_array(expected)}}};

    auto c = tinyinfer::matmul_fp32(a, b, {m}, {k}, {n});
    ASSERT_EQ(c.size(), expected.size());
    for (std::size_t i = 0; i < expected.size(); ++i) {{
        EXPECT_NEAR(c[i], expected[i], {tol:.6g}f) << "mismatch at index " << i;
    }}
}}
"""


def render_softmax_test(
    *,
    suite: str,
    case_name: str,
    x: np.ndarray,
    axis: int,
    expected: np.ndarray,
    tol: float | None = None,
    rationale: str = "",
) -> str:
    # Auto-scale tolerance: softmax outputs live in [0,1] so a tight floor
    # is fine, but raise it slightly on long reductions where summation
    # error accumulates.
    if tol is None:
        n_red = int(x.shape[-1]) if x.ndim >= 1 else 1
        tol = max(1e-5, 1e-6 * n_red)

    x32 = np.asarray(x, dtype=np.float32)
    exp32 = np.asarray(expected, dtype=np.float32)

    # The C++ op is 1D; for batched (2D) inputs we loop over rows so each
    # call exercises softmax_fp32 on one row of length cols.
    if x32.ndim <= 1:
        rows, cols = 1, int(x32.size)
    else:
        if axis not in (-1, x32.ndim - 1):
            raise ValueError(
                f"render_softmax_test: only last-axis softmax is supported, got axis={axis}"
            )
        rows = int(np.prod(x32.shape[:-1]))
        cols = int(x32.shape[-1])

    return f"""\
TEST({suite}, {case_name}) {{
    // {rationale}
    constexpr std::size_t rows = {rows};
    constexpr std::size_t cols = {cols};
    std::vector<float> x = {{{_fmt_float_array(x32)}}};
    std::vector<float> expected = {{{_fmt_float_array(exp32)}}};
    std::vector<float> y(rows * cols, 0.0f);

    for (std::size_t r = 0; r < rows; ++r) {{
        ASSERT_TRUE(tinyinfer::softmax_fp32(x.data() + r * cols, y.data() + r * cols, cols));
    }}
    ASSERT_EQ(y.size(), expected.size());
    for (std::size_t i = 0; i < expected.size(); ++i) {{
        EXPECT_NEAR(y[i], expected[i], {tol:.6g}f) << "mismatch at index " << i;
    }}
}}
"""


def render_layernorm_test(
    *,
    suite: str,
    case_name: str,
    x: np.ndarray,
    eps: float,
    expected: np.ndarray,
    tol: float | None = None,
    rationale: str = "",
) -> str:
    if tol is None:
        max_abs = float(np.max(np.abs(expected))) if expected.size else 1.0
        tol = max(1e-4, max_abs * 1e-4)

    x32 = np.asarray(x, dtype=np.float32)
    exp32 = np.asarray(expected, dtype=np.float32)

    if x32.ndim <= 1:
        rows, cols = 1, int(x32.size)
    else:
        rows = int(np.prod(x32.shape[:-1]))
        cols = int(x32.shape[-1])

    return f"""\
TEST({suite}, {case_name}) {{
    // {rationale}
    constexpr std::size_t rows = {rows};
    constexpr std::size_t cols = {cols};
    constexpr float eps = {eps:.6g}f;
    std::vector<float> x = {{{_fmt_float_array(x32)}}};
    std::vector<float> expected = {{{_fmt_float_array(exp32)}}};
    std::vector<float> y(rows * cols, 0.0f);

    for (std::size_t r = 0; r < rows; ++r) {{
        ASSERT_TRUE(tinyinfer::layernorm_fp32(
            x.data() + r * cols, y.data() + r * cols, cols,
            nullptr, nullptr, eps));
    }}
    ASSERT_EQ(y.size(), expected.size());
    for (std::size_t i = 0; i < expected.size(); ++i) {{
        EXPECT_NEAR(y[i], expected[i], {tol:.6g}f) << "mismatch at index " << i;
    }}
}}
"""


def assemble_file(*, op_name: str, suite: str, body: str) -> RenderedTest:
    header_map = {
        "matmul_fp32": "matmul.hpp",
        "softmax_fp32": "softmax.hpp",
        "layernorm_fp32": "layernorm.hpp",
    }
    header = header_map.get(op_name, f"{op_name}.hpp")
    src = _HEADER.format(header=header) + "\n" + body
    return RenderedTest(
        file_name=f"test_{op_name}_generated.cpp",
        test_suite=suite,
        cpp_source=src,
    )
