"""把生成的测试 case render 成 GTest C++ 源文件。

故意**不**让 LLM 输出数值测试的原始 C++ —— LLM 选 shape / dtype / edge，但
真正的数值由 numpy oracle 算出来，C++ 是我们自己 template 出来的。这就是 devlog
里反复讲的"evidence-grounded test generation"故事。
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np


@dataclass
class RenderedTest:
    file_name: str
    test_suite: str
    cpp_source: str


_HEADER = """\
// AUTO-GENERATED by tinyinfer-agent. DO NOT EDIT BY HAND.
// Reference values computed via numpy oracle.
#include "tinyinfer/{header}"

#include <gtest/gtest.h>

#include <cmath>
#include <vector>
"""


def _fmt_float_array(arr: np.ndarray) -> str:
    flat = np.asarray(arr, dtype=np.float32).reshape(-1)
    return ", ".join(_fmt_float(v) for v in flat.tolist())


def _fmt_float(v: float) -> str:
    """把一个 float 格式化成合法的 C++ literal。

    `f"{v:.7g}f"` 不安全：整数值的 float 会渲染成比如 "1f"，C++ 不认（既没小数点
    也没指数）。这里强制带个小数点，保证结果总是 well-formed 的 float literal。
    """
    s = f"{v:.7g}"
    if not any(c in s for c in (".", "e", "E", "n", "i")):  # n / i 抓 nan / inf
        s = s + ".0"
    return s + "f"


def render_matmul_test(
    *,
    suite: str,
    case_name: str,
    a: np.ndarray,
    b: np.ndarray,
    expected: np.ndarray,
    m: int,
    k: int,
    n: int,
    tol: float | None = None,
    rationale: str = "",
    c_init: np.ndarray | None = None,
) -> str:
    # 按输出量级自动 scale tolerance。fp32 大约 7 位十进制有效数字，所以用
    # 1e-5 的相对容差加 1e-4 的绝对地板。
    if tol is None:
        max_abs = float(np.max(np.abs(expected))) if expected.size else 0.0
        tol = max(1e-4, max_abs * 1e-5)

    if c_init is None:
        # 默认路径：用 vector 重载的 API，c[] 在内部分配并被清零。可读性好，
        # 但**抓不到** "c[] 应被 OVERWRITE 而不是 accumulate" 这条 API 合约
        # 类的 bug。
        return f"""\
TEST({suite}, {case_name}) {{
    // {rationale}
    std::vector<float> a = {{{_fmt_float_array(a)}}};
    std::vector<float> b = {{{_fmt_float_array(b)}}};
    std::vector<float> expected = {{{_fmt_float_array(expected)}}};

    auto c = tinyinfer::matmul_fp32(a, b, {m}, {k}, {n});
    ASSERT_EQ(c.size(), expected.size());
    for (std::size_t i = 0; i < expected.size(); ++i) {{
        EXPECT_NEAR(c[i], expected[i], {tol:.6g}f) << "mismatch at index " << i;
    }}
}}
"""

    # 指针 API 路径：caller 自己分配 c[] 并预填非零 garbage。能抓住
    # 把 c[i*n+j] 当成 acc 初值读的 accumulator 类型 bug（benchmark seed 03）。
    return f"""\
TEST({suite}, {case_name}) {{
    // {rationale}
    std::vector<float> a = {{{_fmt_float_array(a)}}};
    std::vector<float> b = {{{_fmt_float_array(b)}}};
    std::vector<float> expected = {{{_fmt_float_array(expected)}}};
    // Output buffer 预填非零 garbage。正确实现必须 OVERWRITE 每个 c[i*n+j]，
    // 不能 accumulate 进去。
    std::vector<float> c = {{{_fmt_float_array(c_init)}}};

    ASSERT_TRUE(tinyinfer::matmul_fp32(a.data(), b.data(), c.data(), {m}, {k}, {n}));
    ASSERT_EQ(c.size(), expected.size());
    for (std::size_t i = 0; i < expected.size(); ++i) {{
        EXPECT_NEAR(c[i], expected[i], {tol:.6g}f) << "mismatch at index " << i;
    }}
}}
"""


def render_softmax_test(
    *,
    suite: str,
    case_name: str,
    x: np.ndarray,
    axis: int,
    expected: np.ndarray,
    tol: float | None = None,
    rationale: str = "",
) -> str:
    # 自动 scale tolerance：softmax 输出在 [0,1]，所以容差地板可以紧；但 long
    # reduction 累加误差会涨，长度大时把容差稍微抬高一点。
    if tol is None:
        n_red = int(x.shape[-1]) if x.ndim >= 1 else 1
        tol = max(1e-5, 1e-6 * n_red)

    x32 = np.asarray(x, dtype=np.float32)
    exp32 = np.asarray(expected, dtype=np.float32)

    # C++ op 是 1D；batched (2D) input 时按 row 循环，每次 call 对一行 cols
    # 调用 softmax_fp32。
    if x32.ndim <= 1:
        rows, cols = 1, int(x32.size)
    else:
        if axis not in (-1, x32.ndim - 1):
            raise ValueError(
                f"render_softmax_test: only last-axis softmax is supported, got axis={axis}"
            )
        rows = int(np.prod(x32.shape[:-1]))
        cols = int(x32.shape[-1])

    return f"""\
TEST({suite}, {case_name}) {{
    // {rationale}
    constexpr std::size_t rows = {rows};
    constexpr std::size_t cols = {cols};
    std::vector<float> x = {{{_fmt_float_array(x32)}}};
    std::vector<float> expected = {{{_fmt_float_array(exp32)}}};
    std::vector<float> y(rows * cols, 0.0f);

    for (std::size_t r = 0; r < rows; ++r) {{
        ASSERT_TRUE(tinyinfer::softmax_fp32(x.data() + r * cols, y.data() + r * cols, cols));
    }}
    ASSERT_EQ(y.size(), expected.size());
    for (std::size_t i = 0; i < expected.size(); ++i) {{
        EXPECT_NEAR(y[i], expected[i], {tol:.6g}f) << "mismatch at index " << i;
    }}
}}
"""


def render_layernorm_test(
    *,
    suite: str,
    case_name: str,
    x: np.ndarray,
    eps: float,
    expected: np.ndarray,
    tol: float | None = None,
    rationale: str = "",
) -> str:
    if tol is None:
        max_abs = float(np.max(np.abs(expected))) if expected.size else 1.0
        tol = max(1e-4, max_abs * 1e-4)

    x32 = np.asarray(x, dtype=np.float32)
    exp32 = np.asarray(expected, dtype=np.float32)

    if x32.ndim <= 1:
        rows, cols = 1, int(x32.size)
    else:
        rows = int(np.prod(x32.shape[:-1]))
        cols = int(x32.shape[-1])

    return f"""\
TEST({suite}, {case_name}) {{
    // {rationale}
    constexpr std::size_t rows = {rows};
    constexpr std::size_t cols = {cols};
    constexpr float eps = {eps:.6g}f;
    std::vector<float> x = {{{_fmt_float_array(x32)}}};
    std::vector<float> expected = {{{_fmt_float_array(exp32)}}};
    std::vector<float> y(rows * cols, 0.0f);

    for (std::size_t r = 0; r < rows; ++r) {{
        ASSERT_TRUE(tinyinfer::layernorm_fp32(
            x.data() + r * cols, y.data() + r * cols, cols,
            nullptr, nullptr, eps));
    }}
    ASSERT_EQ(y.size(), expected.size());
    for (std::size_t i = 0; i < expected.size(); ++i) {{
        EXPECT_NEAR(y[i], expected[i], {tol:.6g}f) << "mismatch at index " << i;
    }}
}}
"""


def assemble_file(*, op_name: str, suite: str, body: str) -> RenderedTest:
    header_map = {
        "matmul_fp32": "matmul.hpp",
        "softmax_fp32": "softmax.hpp",
        "layernorm_fp32": "layernorm.hpp",
    }
    header = header_map.get(op_name, f"{op_name}.hpp")
    src = _HEADER.format(header=header) + "\n" + body
    return RenderedTest(
        file_name=f"test_{op_name}_generated.cpp",
        test_suite=suite,
        cpp_source=src,
    )
