"""内存安全 skill。

我们不打算把 ASan 接进 CMake build（对生成测试来说太重）。改用 guard-band
测试：在活跃区域两侧用 sentinel 字节填 buffer，跑 op 很多次（每次新分配，
让 allocator 路径承压），然后验证 sentinel 还在。这能抓到：

  - 越界写到 output buffer 末尾之外
  - 写过 input buffer 起始之前
  - 每次迭代涨内存的 leak（测试循环够大，真泄漏会从 RSS 压力上明显看出来）

完整的 leak / use-after-free 覆盖需要开发者用 `-fsanitize=address`（gcc/clang）
或 `/fsanitize=address`（MSVC）重 build。生成的测试不论如何都能过 —— sanitizer
是包裹，不是替代。
"""

from __future__ import annotations

from typing import Optional

from agent.llm import LLMClient
from agent.skills.base import Skill
from agent.state import ChangedOp, SkillKind, TestCase


# 按 op 给的 (case 名, params, loop_iters) tuple。
_MEM_PLANS: dict[str, list[dict]] = {
    "matmul_fp32": [
        {"name": "memory_guard_bands_small", "m": 4, "k": 4, "n": 4, "iters": 256},
        {"name": "memory_repeat_alloc_medium", "m": 16, "k": 32, "n": 16, "iters": 64},
    ],
    "softmax_fp32": [
        {"name": "memory_guard_bands_small", "n": 16, "iters": 512},
        {"name": "memory_repeat_alloc_medium", "n": 128, "iters": 256},
    ],
    "layernorm_fp32": [
        {"name": "memory_guard_bands_small", "n": 16, "iters": 512},
        {"name": "memory_repeat_alloc_medium", "n": 128, "iters": 256},
    ],
}


_HEADER_BY_OP = {
    "matmul_fp32": "matmul.hpp",
    "softmax_fp32": "softmax.hpp",
    "layernorm_fp32": "layernorm.hpp",
}


_FILE_PROLOGUE = """\
// AUTO-GENERATED by tinyinfer-agent (memory skill). DO NOT EDIT BY HAND.
// Guard-band tests: sentinel bytes around the active buffer must remain
// untouched after the op runs. Rebuild with -fsanitize=address for full
// leak / UAF coverage.
#include "tinyinfer/{header}"

#include <gtest/gtest.h>

#include <cstddef>
#include <cstdint>
#include <vector>

namespace {{
constexpr std::uint32_t kGuard = 0xDEADBEEFu;

// Allocate `n` floats with one guard word on each side. Returns the
// address of the active region and stamps guard words into the padding.
inline float* make_guarded(std::vector<std::uint32_t>& storage, std::size_t n_floats) {{
    // 1 guard word + n_floats words + 1 guard word, all uint32-sized.
    storage.assign(n_floats + 2, 0u);
    storage.front() = kGuard;
    storage.back() = kGuard;
    return reinterpret_cast<float*>(&storage[1]);
}}

inline bool guards_intact(const std::vector<std::uint32_t>& storage) {{
    return storage.front() == kGuard && storage.back() == kGuard;
}}
}}
"""


def _matmul_case(p: dict) -> str:
    m, k, n = p["m"], p["k"], p["n"]
    return f"""\
TEST(MatmulMemory, {p['name']}) {{
    constexpr std::size_t m = {m}, k = {k}, n = {n};
    for (int it = 0; it < {p['iters']}; ++it) {{
        std::vector<std::uint32_t> sa, sb, sc;
        float* a = make_guarded(sa, m * k);
        float* b = make_guarded(sb, k * n);
        float* c = make_guarded(sc, m * n);
        for (std::size_t i = 0; i < m * k; ++i) a[i] = 0.5f;
        for (std::size_t i = 0; i < k * n; ++i) b[i] = 0.25f;

        ASSERT_TRUE(tinyinfer::matmul_fp32(a, b, c, m, k, n));

        EXPECT_TRUE(guards_intact(sa)) << "input A guard clobbered at iter " << it;
        EXPECT_TRUE(guards_intact(sb)) << "input B guard clobbered at iter " << it;
        EXPECT_TRUE(guards_intact(sc)) << "output C guard clobbered at iter " << it;
    }}
}}
"""


def _vector_case(op_name: str, p: dict) -> str:
    n = p["n"]
    suite = "SoftmaxMemory" if op_name == "softmax_fp32" else "LayernormMemory"
    op_call = (
        "tinyinfer::softmax_fp32(x, y, n)"
        if op_name == "softmax_fp32"
        else "tinyinfer::layernorm_fp32(x, y, n, nullptr, nullptr, 1e-5f)"
    )
    return f"""\
TEST({suite}, {p['name']}) {{
    constexpr std::size_t n = {n};
    for (int it = 0; it < {p['iters']}; ++it) {{
        std::vector<std::uint32_t> sx, sy;
        float* x = make_guarded(sx, n);
        float* y = make_guarded(sy, n);
        for (std::size_t i = 0; i < n; ++i) x[i] = 0.5f;

        ASSERT_TRUE({op_call});

        EXPECT_TRUE(guards_intact(sx)) << "input guard clobbered at iter " << it;
        EXPECT_TRUE(guards_intact(sy)) << "output guard clobbered at iter " << it;
    }}
}}
"""


class MemorySkill(Skill):
    kind = SkillKind.MEMORY
    activation_keywords = [
        "malloc", "free", "new ", "delete ", "alloc", "buffer", "memcpy",
        "memset", "resize", "reserve", "allocator", "leak", "ub-", "asan",
    ]

    def __init__(self, llm: Optional[LLMClient] = None):
        self.llm = llm

    def required_coverage_dimensions(self) -> list[str]:
        return ["guard_band", "repeated_alloc"]

    def generate(self, op: ChangedOp) -> list[TestCase]:
        plans = _MEM_PLANS.get(op.name)
        if not plans:
            return []

        header = _HEADER_BY_OP.get(op.name, f"{op.name}.hpp")
        bodies: list[str] = []
        out: list[TestCase] = []

        for p in plans:
            if op.name == "matmul_fp32":
                bodies.append(_matmul_case(p))
            elif op.name in ("softmax_fp32", "layernorm_fp32"):
                bodies.append(_vector_case(op.name, p))
            out.append(
                TestCase(
                    op_name=op.name,
                    skill=self.kind,
                    test_name=p["name"],
                    cpp_source="",
                    rationale="guard-band + repeated-alloc stress",
                )
            )

        src = _FILE_PROLOGUE.format(header=header) + "\n" + "\n".join(bodies)
        for tc in out:
            tc.cpp_source = src
            tc.inputs = {"file_suffix": "memory"}
        return out