"""Memory-safety skill.

We don't try to plumb ASan into the CMake build (too invasive for a generated
test). Instead we emit guard-band tests: allocate buffers with sentinel bytes
on either side of the active region, run the op many times (with fresh
allocations each iteration to stress the allocator path), then verify the
sentinels are intact. This catches:

  - off-by-one writes past the end of the output buffer
  - clobbers past the beginning of the input buffer
  - leaks that grow per-iteration memory (the test loop is large enough that
    a real leak shows up as obvious RSS pressure)

For full leak / use-after-free coverage, the developer should rebuild with
`-fsanitize=address` (gcc/clang) or `/fsanitize=address` (MSVC). The
generated test still passes either way — sanitizers wrap, not replace, it.
"""

from __future__ import annotations

from typing import Optional

from agent.llm import LLMClient
from agent.skills.base import Skill
from agent.state import ChangedOp, SkillKind, TestCase


# Per-op (case name, params, loop_iters) tuples.
_MEM_PLANS: dict[str, list[dict]] = {
    "matmul_fp32": [
        {"name": "memory_guard_bands_small", "m": 4, "k": 4, "n": 4, "iters": 256},
        {"name": "memory_repeat_alloc_medium", "m": 16, "k": 32, "n": 16, "iters": 64},
    ],
    "softmax_fp32": [
        {"name": "memory_guard_bands_small", "n": 16, "iters": 512},
        {"name": "memory_repeat_alloc_medium", "n": 128, "iters": 256},
    ],
    "layernorm_fp32": [
        {"name": "memory_guard_bands_small", "n": 16, "iters": 512},
        {"name": "memory_repeat_alloc_medium", "n": 128, "iters": 256},
    ],
}


_HEADER_BY_OP = {
    "matmul_fp32": "matmul.hpp",
    "softmax_fp32": "softmax.hpp",
    "layernorm_fp32": "layernorm.hpp",
}


_FILE_PROLOGUE = """\
// AUTO-GENERATED by tinyinfer-agent (memory skill). DO NOT EDIT BY HAND.
// Guard-band tests: sentinel bytes around the active buffer must remain
// untouched after the op runs. Rebuild with -fsanitize=address for full
// leak / UAF coverage.
#include "tinyinfer/{header}"

#include <gtest/gtest.h>

#include <cstddef>
#include <cstdint>
#include <vector>

namespace {{
constexpr std::uint32_t kGuard = 0xDEADBEEFu;

// Allocate `n` floats with one guard word on each side. Returns the
// address of the active region and stamps guard words into the padding.
inline float* make_guarded(std::vector<std::uint32_t>& storage, std::size_t n_floats) {{
    // 1 guard word + n_floats words + 1 guard word, all uint32-sized.
    storage.assign(n_floats + 2, 0u);
    storage.front() = kGuard;
    storage.back() = kGuard;
    return reinterpret_cast<float*>(&storage[1]);
}}

inline bool guards_intact(const std::vector<std::uint32_t>& storage) {{
    return storage.front() == kGuard && storage.back() == kGuard;
}}
}}
"""


def _matmul_case(p: dict) -> str:
    m, k, n = p["m"], p["k"], p["n"]
    return f"""\
TEST(MatmulMemory, {p['name']}) {{
    constexpr std::size_t m = {m}, k = {k}, n = {n};
    for (int it = 0; it < {p['iters']}; ++it) {{
        std::vector<std::uint32_t> sa, sb, sc;
        float* a = make_guarded(sa, m * k);
        float* b = make_guarded(sb, k * n);
        float* c = make_guarded(sc, m * n);
        for (std::size_t i = 0; i < m * k; ++i) a[i] = 0.5f;
        for (std::size_t i = 0; i < k * n; ++i) b[i] = 0.25f;

        ASSERT_TRUE(tinyinfer::matmul_fp32(a, b, c, m, k, n));

        EXPECT_TRUE(guards_intact(sa)) << "input A guard clobbered at iter " << it;
        EXPECT_TRUE(guards_intact(sb)) << "input B guard clobbered at iter " << it;
        EXPECT_TRUE(guards_intact(sc)) << "output C guard clobbered at iter " << it;
    }}
}}
"""


def _vector_case(op_name: str, p: dict) -> str:
    n = p["n"]
    suite = "SoftmaxMemory" if op_name == "softmax_fp32" else "LayernormMemory"
    op_call = (
        "tinyinfer::softmax_fp32(x, y, n)"
        if op_name == "softmax_fp32"
        else "tinyinfer::layernorm_fp32(x, y, n, nullptr, nullptr, 1e-5f)"
    )
    return f"""\
TEST({suite}, {p['name']}) {{
    constexpr std::size_t n = {n};
    for (int it = 0; it < {p['iters']}; ++it) {{
        std::vector<std::uint32_t> sx, sy;
        float* x = make_guarded(sx, n);
        float* y = make_guarded(sy, n);
        for (std::size_t i = 0; i < n; ++i) x[i] = 0.5f;

        ASSERT_TRUE({op_call});

        EXPECT_TRUE(guards_intact(sx)) << "input guard clobbered at iter " << it;
        EXPECT_TRUE(guards_intact(sy)) << "output guard clobbered at iter " << it;
    }}
}}
"""


class MemorySkill(Skill):
    kind = SkillKind.MEMORY
    activation_keywords = [
        "malloc", "free", "new ", "delete ", "alloc", "buffer", "memcpy",
        "memset", "resize", "reserve", "allocator", "leak", "ub-", "asan",
    ]

    def __init__(self, llm: Optional[LLMClient] = None):
        self.llm = llm

    def required_coverage_dimensions(self) -> list[str]:
        return ["guard_band", "repeated_alloc"]

    def generate(self, op: ChangedOp) -> list[TestCase]:
        plans = _MEM_PLANS.get(op.name)
        if not plans:
            return []

        header = _HEADER_BY_OP.get(op.name, f"{op.name}.hpp")
        bodies: list[str] = []
        out: list[TestCase] = []

        for p in plans:
            if op.name == "matmul_fp32":
                bodies.append(_matmul_case(p))
            elif op.name in ("softmax_fp32", "layernorm_fp32"):
                bodies.append(_vector_case(op.name, p))
            out.append(
                TestCase(
                    op_name=op.name,
                    skill=self.kind,
                    test_name=p["name"],
                    cpp_source="",
                    rationale="guard-band + repeated-alloc stress",
                )
            )

        src = _FILE_PROLOGUE.format(header=header) + "\n" + "\n".join(bodies)
        for tc in out:
            tc.cpp_source = src
            tc.inputs = {"file_suffix": "memory"}
        return out