"""Performance (latency-regression) skill.

We emit chrono-based microbenchmarks as GTest cases rather than a separate
Google Benchmark binary — this lets the same `ctest` pipeline catch latency
regressions without adding a new build dependency.

Strategy:
  - One C++ file per op containing N perf cases.
  - Each case runs warmup + measure iterations on a single representative
    shape and asserts the median per-iter latency stays under a generous
    budget. The intent is to fail loudly on order-of-magnitude regressions
    (eg. a 10x slowdown from an algorithmic change), not micro-tune.

The budget is intentionally loose. A real project should baseline on its
own CI hardware and ratchet down from there.
"""

from __future__ import annotations

from typing import Optional

import numpy as np

from agent.llm import LLMClient
from agent.skills.base import Skill
from agent.state import ChangedOp, SkillKind, TestCase


# Per-op (case name, params, budget_us) tuples. The budget is set loose so
# the test serves as a regression alarm, not a perf certificate.
_PERF_PLANS: dict[str, list[dict]] = {
    "matmul_fp32": [
        {"name": "perf_small_16x16x16", "m": 16, "k": 16, "n": 16, "iters": 200, "budget_us": 200.0},
        {"name": "perf_medium_64x64x64", "m": 64, "k": 64, "n": 64, "iters": 50, "budget_us": 5_000.0},
        {"name": "perf_aligned_32x32x32", "m": 32, "k": 32, "n": 32, "iters": 100, "budget_us": 1_500.0},
    ],
    "softmax_fp32": [
        {"name": "perf_small_n32", "n": 32, "iters": 500, "budget_us": 50.0},
        {"name": "perf_aligned_n128", "n": 128, "iters": 200, "budget_us": 200.0},
        {"name": "perf_thin_n8", "n": 8, "iters": 1000, "budget_us": 20.0},
    ],
    "layernorm_fp32": [
        {"name": "perf_small_n32", "n": 32, "iters": 500, "budget_us": 50.0},
        {"name": "perf_aligned_n128", "n": 128, "iters": 200, "budget_us": 200.0},
        {"name": "perf_thin_n8", "n": 8, "iters": 1000, "budget_us": 20.0},
    ],
}


_HEADER_BY_OP = {
    "matmul_fp32": "matmul.hpp",
    "softmax_fp32": "softmax.hpp",
    "layernorm_fp32": "layernorm.hpp",
}


_FILE_PROLOGUE = """\
// AUTO-GENERATED by tinyinfer-agent (perf skill). DO NOT EDIT BY HAND.
// chrono-based microbenchmarks emitted as GTest cases. Budgets are loose:
// the intent is to catch order-of-magnitude regressions, not certify perf.
#include "tinyinfer/{header}"

#include <gtest/gtest.h>

#include <algorithm>
#include <chrono>
#include <cstddef>
#include <vector>

namespace {{
inline double median_us(std::vector<double> ts) {{
    std::sort(ts.begin(), ts.end());
    const std::size_t n = ts.size();
    if (n == 0) return 0.0;
    return (n % 2 == 1) ? ts[n / 2] : 0.5 * (ts[n / 2 - 1] + ts[n / 2]);
}}
}}
"""


def _matmul_case(p: dict) -> str:
    m, k, n = p["m"], p["k"], p["n"]
    return f"""\
TEST(MatmulPerf, {p['name']}) {{
    constexpr std::size_t m = {m}, k = {k}, n = {n};
    std::vector<float> a(m * k, 0.5f);
    std::vector<float> b(k * n, 0.25f);
    std::vector<float> c(m * n, 0.0f);

    // Warmup.
    for (int w = 0; w < 5; ++w) {{
        tinyinfer::matmul_fp32(a.data(), b.data(), c.data(), m, k, n);
    }}

    std::vector<double> samples;
    samples.reserve({p['iters']});
    for (int i = 0; i < {p['iters']}; ++i) {{
        const auto t0 = std::chrono::steady_clock::now();
        tinyinfer::matmul_fp32(a.data(), b.data(), c.data(), m, k, n);
        const auto t1 = std::chrono::steady_clock::now();
        samples.push_back(
            std::chrono::duration<double, std::micro>(t1 - t0).count());
    }}
    const double med = median_us(samples);
    EXPECT_LT(med, {p['budget_us']:g}) << "median per-iter latency exceeded budget";
}}
"""


def _vector_case(op_name: str, p: dict) -> str:
    n = p["n"]
    op_call = (
        f"tinyinfer::softmax_fp32(x.data(), y.data(), n)"
        if op_name == "softmax_fp32"
        else f"tinyinfer::layernorm_fp32(x.data(), y.data(), n, nullptr, nullptr, 1e-5f)"
    )
    suite = "SoftmaxPerf" if op_name == "softmax_fp32" else "LayernormPerf"
    return f"""\
TEST({suite}, {p['name']}) {{
    constexpr std::size_t n = {n};
    std::vector<float> x(n, 0.5f);
    std::vector<float> y(n, 0.0f);

    for (int w = 0; w < 5; ++w) {{ {op_call}; }}

    std::vector<double> samples;
    samples.reserve({p['iters']});
    for (int i = 0; i < {p['iters']}; ++i) {{
        const auto t0 = std::chrono::steady_clock::now();
        {op_call};
        const auto t1 = std::chrono::steady_clock::now();
        samples.push_back(
            std::chrono::duration<double, std::micro>(t1 - t0).count());
    }}
    const double med = median_us(samples);
    EXPECT_LT(med, {p['budget_us']:g}) << "median per-iter latency exceeded budget";
}}
"""


class PerformanceSkill(Skill):
    kind = SkillKind.PERFORMANCE
    activation_keywords = [
        "simd", "vectorise", "vectorize", "unroll", "tile", "block", "cache",
        "inline", "hot", "loop reorder", "fastpath", "fast path",
    ]

    def __init__(self, llm: Optional[LLMClient] = None):
        self.llm = llm

    def required_coverage_dimensions(self) -> list[str]:
        return ["small_shape", "aligned_shape"]

    def generate(self, op: ChangedOp) -> list[TestCase]:
        plans = _PERF_PLANS.get(op.name)
        if not plans:
            return []

        header = _HEADER_BY_OP.get(op.name, f"{op.name}.hpp")
        bodies: list[str] = []
        out: list[TestCase] = []

        for p in plans:
            if op.name == "matmul_fp32":
                bodies.append(_matmul_case(p))
            elif op.name in ("softmax_fp32", "layernorm_fp32"):
                bodies.append(_vector_case(op.name, p))
            out.append(
                TestCase(
                    op_name=op.name,
                    skill=self.kind,
                    test_name=p["name"],
                    cpp_source="",
                    rationale=f"perf budget {p['budget_us']:g}us median",
                )
            )

        # We write a separate file (with _perf suffix) so a single op can
        # have both a numerical and a perf generated test file side-by-side.
        src = _FILE_PROLOGUE.format(header=header) + "\n" + "\n".join(bodies)
        for tc in out:
            tc.cpp_source = src
            # Used by install_tests_node to disambiguate filenames.
            tc.inputs = {"file_suffix": "perf"}
        return out